export const GenderOptions = ["Bărbat", "Femeie"];

export const BloodTypes = ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-", "Necunoscută"];

export const SmokingStatusOptions = [
  "Nefumător",
  "Fumător activ",
  "Fumător ocazional",
  "Fost fumător",
];

export const AlcoholConsumptionOptions = [
  "Nu consumă",
  "Consum ocazional",
  "Consum moderat",
  "Consum frecvent",
];

export const ExerciseFrequencyOptions = [
  "Nu fac exerciții",
  "Rar (1-2 ori/lună)",
  "Ocazional (1-2 ori/săptămână)",
  "Frecvent (3-5 ori/săptămână)",
  "Zilnic",
];

export const PatientFormDefaultValues = {
  firstName: "",
  lastName: "",
  email: "",
  phone: "",
  birthDate: new Date(Date.now()),
  gender: "Bărbat" as Gender,
  address: "",
  occupation: "",
  emergencyContactName: "",
  emergencyContactNumber: "",
  primaryPhysician: "",
  insuranceProvider: "",
  insurancePolicyNumber: "",
  allergies: "",
  currentMedication: "",
  familyMedicalHistory: "",
  pastMedicalHistory: "",
  identificationType: "Card de identitate (CI)",
  identificationNumber: "",
  identificationDocument: [],
  treatmentConsent: false,
  disclosureConsent: false,
  privacyConsent: false,
  bloodType: "",
  height: undefined,
  weight: undefined,
  cardiovascularDiseases: "",
  chronicDiseases: "",
  surgeries: "",
  vaccinations: "",
  smokingStatus: "",
  alcoholConsumption: "",
  exerciseFrequency: "",
};

export const IdentificationTypes = [
  "Card de identitate (CI)",
  "Pașaport",
  "Card de sănătate",
  "CNP (Cod Numeric Personal)",
  "Permis de conducere",
  "Certificat de naștere",
  "Carte de identitate provizorie",
];

// Specializări medicale
export const MedicalSpecialties = [
  "Cardiologie",
  "Dermatologie",
  "Endocrinologie",
  "Gastroenterologie",
  "Neurologie",
  "Oftalmologie",
  "Ortopedie",
  "Pediatrie",
  "Psihiatrie",
  "Urologie",
  "Analize medicale",
];

// Pachete de analize medicale
export interface AnalysisPackage {
  id: string;
  name: string;
  description: string;
  price: number;
  specialties: string[]; // Specializările pentru care este disponibil
  gender?: "Bărbat" | "Femeie" | "Ambele"; // Genul pentru care este disponibil
  tests: string[]; // Lista de analize incluse
}

export const AnalysisPackages: AnalysisPackage[] = [
  // Pachete generale
  {
    id: "general-complete",
    name: "Pachet Analize Complete",
    description: "Set complet de analize de bază pentru evaluarea generală a sănătății",
    price: 250,
    specialties: ["Analize medicale"],
    gender: "Ambele",
    tests: [
      "Hemoleucogramă completă",
      "Glicemie",
      "Colesterol total",
      "HDL colesterol",
      "LDL colesterol",
      "Trigliceride",
      "Creatinină",
      "Uree",
      "ALT (GPT)",
      "AST (GOT)",
      "TSH",
      "FT4",
      "Vitamina D",
      "Vitamina B12",
      "Acid folic",
    ],
  },
  {
    id: "general-basic",
    name: "Pachet Analize de Bază",
    description: "Set minim de analize pentru screening general",
    price: 120,
    specialties: ["Analize medicale"],
    gender: "Ambele",
    tests: [
      "Hemoleucogramă",
      "Glicemie",
      "Colesterol total",
      "Creatinină",
      "TSH",
    ],
  },
  // Pachete pentru bărbați
  {
    id: "male-complete",
    name: "Pachet Analize Complete - Bărbați",
    description: "Set complet de analize specifice pentru bărbați",
    price: 350,
    specialties: ["Analize medicale", "Urologie"],
    gender: "Bărbat",
    tests: [
      "Hemoleucogramă completă",
      "Glicemie",
      "Colesterol total",
      "HDL colesterol",
      "LDL colesterol",
      "Trigliceride",
      "PSA total",
      "PSA liber",
      "Testosteron",
      "Creatinină",
      "Uree",
      "ALT (GPT)",
      "AST (GOT)",
      "TSH",
      "FT4",
    ],
  },
  {
    id: "male-prostate",
    name: "Pachet Screening Prostată",
    description: "Analize specifice pentru evaluarea sănătății prostatice",
    price: 180,
    specialties: ["Analize medicale", "Urologie"],
    gender: "Bărbat",
    tests: [
      "PSA total",
      "PSA liber",
      "Raport PSA liber/PSA total",
      "Creatinină",
    ],
  },
  // Pachete pentru femei
  {
    id: "female-complete",
    name: "Pachet Analize Complete - Femei",
    description: "Set complet de analize specifice pentru femei",
    price: 380,
    specialties: ["Analize medicale", "Ginecologie"],
    gender: "Femeie",
    tests: [
      "Hemoleucogramă completă",
      "Glicemie",
      "Colesterol total",
      "HDL colesterol",
      "LDL colesterol",
      "Trigliceride",
      "Creatinină",
      "Uree",
      "ALT (GPT)",
      "AST (GOT)",
      "TSH",
      "FT4",
      "Estradiol",
      "Progesteron",
      "Testosteron",
      "Vitamina D",
      "Feritină",
    ],
  },
  {
    id: "female-hormonal",
    name: "Pachet Analize Hormonale - Femei",
    description: "Evaluare hormonală completă pentru femei",
    price: 280,
    specialties: ["Analize medicale", "Ginecologie", "Endocrinologie"],
    gender: "Femeie",
    tests: [
      "TSH",
      "FT4",
      "FT3",
      "Estradiol",
      "Progesteron",
      "Testosteron",
      "Prolactină",
      "FSH",
      "LH",
    ],
  },
  {
    id: "female-pregnancy",
    name: "Pachet Analize Sarcina",
    description: "Analize pentru monitorizarea sarcinii",
    price: 320,
    specialties: ["Analize medicale", "Ginecologie"],
    gender: "Femeie",
    tests: [
      "Hemoleucogramă completă",
      "Glicemie",
      "TSH",
      "FT4",
      "Vitamina D",
      "Acid folic",
      "Feritină",
      "Grupa sanguină și Rh",
      "Anticorpi anti-Rh",
    ],
  },
  // Pachete pentru specializări specifice
  {
    id: "cardiology",
    name: "Pachet Analize Cardiologice",
    description: "Evaluare completă a sănătății cardiovasculare",
    price: 300,
    specialties: ["Analize medicale", "Cardiologie"],
    gender: "Ambele",
    tests: [
      "Hemoleucogramă",
      "Glicemie",
      "Colesterol total",
      "HDL colesterol",
      "LDL colesterol",
      "Trigliceride",
      "Homocisteină",
      "NT-proBNP",
      "Troponină",
      "Creatinină",
      "Uree",
    ],
  },
  {
    id: "endocrinology",
    name: "Pachet Analize Endocrinologice",
    description: "Evaluare completă a funcției endocrine",
    price: 350,
    specialties: ["Analize medicale", "Endocrinologie"],
    gender: "Ambele",
    tests: [
      "TSH",
      "FT4",
      "FT3",
      "Anticorpi anti-TPO",
      "Anticorpi anti-TG",
      "Cortizol",
      "Insulină",
      "HbA1c",
      "Vitamina D",
      "Calciu",
      "Fosfor",
    ],
  },
  {
    id: "gastroenterology",
    name: "Pachet Analize Gastroenterologice",
    description: "Evaluare completă a funcției digestive",
    price: 320,
    specialties: ["Analize medicale", "Gastroenterologie"],
    gender: "Ambele",
    tests: [
      "Hemoleucogramă",
      "ALT (GPT)",
      "AST (GOT)",
      "GGT",
      "Fosfatază alcalină",
      "Bilirubină totală",
      "Bilirubină directă",
      "Amilază",
      "Lipază",
      "Creatinină",
      "Uree",
    ],
  },
  {
    id: "dermatology",
    name: "Pachet Analize Dermatologice",
    description: "Analize pentru evaluarea sănătății pielii",
    price: 280,
    specialties: ["Analize medicale", "Dermatologie"],
    gender: "Ambele",
    tests: [
      "Hemoleucogramă",
      "Vitamina D",
      "Vitamina B12",
      "Acid folic",
      "Feritină",
      "Zinc",
      "Seleniu",
      "TSH",
      "FT4",
    ],
  },
];

export const Doctors: Doctor[] = [
  {
    image: "/assets/images/b_48.png",
    name: "Dr. Ion Popescu",
    specialty: "Cardiologie",
    age: 48,
    education: [
      { degree: "Doctorat în Medicină", institution: "Universitatea de Medicină și Farmacie Carol Davila", country: "România", year: 2000 },
      { degree: "Specializare Cardiologie", institution: "Spitalul Universitar de Urgență București", country: "România", year: 2005 },
      { degree: "Fellowship Cardiologie Intervențională", institution: "Mayo Clinic", country: "Străinătate", year: 2008 },
    ],
    experience: 20,
    additionalSpecializations: ["Ecocardiografie", "Holter EKG", "Test de efort"],
    languages: ["Română", "Engleză", "Franceză"],
    certifications: ["Certificat European de Cardiologie", "Certificat în Cardiologie Intervențională"],
  },
  {
    image: "/assets/images/f_43.png",
    name: "Dr. Maria Ionescu",
    specialty: "Dermatologie",
    age: 42,
    education: [
      { degree: "Doctorat în Medicină", institution: "Universitatea de Medicină și Farmacie Victor Babeș Timișoara", country: "România", year: 2005 },
      { degree: "Specializare Dermatologie", institution: "Spitalul Clinic de Urgență Timișoara", country: "România", year: 2010 },
      { degree: "Master în Dermatologie Estetică", institution: "Université Paris Descartes", country: "Străinătate", year: 2012 },
    ],
    experience: 15,
    additionalSpecializations: ["Dermatologie Estetică", "Dermatoscopie", "Tratament cu laser"],
    languages: ["Română", "Engleză", "Franceză"],
    certifications: ["Certificat European de Dermatologie", "Certificat în Dermatologie Estetică"],
  },
  {
    image: "/assets/images/b_42.png",
    name: "Dr. Alexandru Georgescu",
    specialty: "Endocrinologie",
    age: 45,
    education: [
      { degree: "Doctorat în Medicină", institution: "Universitatea de Medicină și Farmacie Grigore T. Popa Iași", country: "România", year: 2002 },
      { degree: "Specializare Endocrinologie", institution: "Institutul de Endocrinologie C.I. Parhon", country: "România", year: 2007 },
      { degree: "Fellowship Diabetologie", institution: "Joslin Diabetes Center", country: "Străinătate", year: 2010 },
    ],
    experience: 18,
    additionalSpecializations: ["Diabetologie", "Boli metabolice", "Boli tiroidiene"],
    languages: ["Română", "Engleză"],
    certifications: ["Certificat European de Endocrinologie", "Certificat în Diabetologie"],
  },
  {
    image: "/assets/images/f_40.png",
    name: "Dr. Elena Radu",
    specialty: "Gastroenterologie",
    age: 40,
    education: [
      { degree: "Doctorat în Medicină", institution: "Universitatea de Medicină și Farmacie Carol Davila", country: "România", year: 2007 },
      { degree: "Specializare Gastroenterologie", institution: "Spitalul Universitar de Urgență București", country: "România", year: 2012 },
      { degree: "Fellowship Endoscopie Digestivă", institution: "Cleveland Clinic", country: "Străinătate", year: 2014 },
    ],
    experience: 13,
    additionalSpecializations: ["Endoscopie digestivă", "Hepatologie", "Boli inflamatorii intestinale"],
    languages: ["Română", "Engleză", "Germană"],
    certifications: ["Certificat European de Gastroenterologie", "Certificat în Endoscopie Digestivă"],
  },
  {
    image: "/assets/images/b_50.png",
    name: "Dr. Andrei Stanciu",
    specialty: "Neurologie",
    age: 50,
    education: [
      { degree: "Doctorat în Medicină", institution: "Universitatea de Medicină și Farmacie Carol Davila", country: "România", year: 1998 },
      { degree: "Specializare Neurologie", institution: "Spitalul Universitar de Urgență București", country: "România", year: 2003 },
      { degree: "Fellowship Neurovascular", institution: "Massachusetts General Hospital", country: "Străinătate", year: 2006 },
    ],
    experience: 22,
    additionalSpecializations: ["Neurologie vasculară", "Epilepsie", "Boli neurodegenerative"],
    languages: ["Română", "Engleză"],
    certifications: ["Certificat European de Neurologie", "Certificat în Neurologie Vasculară"],
  },
  {
    image: "/assets/images/f_38.png",
    name: "Dr. Cristina Moldovan",
    specialty: "Oftalmologie",
    age: 38,
    education: [
      { degree: "Doctorat în Medicină", institution: "Universitatea de Medicină și Farmacie Iuliu Hațieganu Cluj-Napoca", country: "România", year: 2009 },
      { degree: "Specializare Oftalmologie", institution: "Spitalul Clinic de Oftalmologie Cluj-Napoca", country: "România", year: 2014 },
      { degree: "Fellowship Chirurgie Refractivă", institution: "Moorfields Eye Hospital", country: "Străinătate", year: 2016 },
    ],
    experience: 11,
    additionalSpecializations: ["Chirurgie refractivă", "Retină", "Glaucom"],
    languages: ["Română", "Engleză"],
    certifications: ["Certificat European de Oftalmologie", "Certificat în Chirurgie Refractivă"],
  },
  {
    image: "/assets/images/b_56.png",
    name: "Dr. Florin Dumitrescu",
    specialty: "Ortopedie",
    age: 46,
    education: [
      { degree: "Doctorat în Medicină", institution: "Universitatea de Medicină și Farmacie Carol Davila", country: "România", year: 2001 },
      { degree: "Specializare Ortopedie", institution: "Spitalul Universitar de Urgență București", country: "România", year: 2006 },
      { degree: "Fellowship Chirurgie Artroscopă", institution: "Hospital for Special Surgery", country: "Străinătate", year: 2009 },
    ],
    experience: 19,
    additionalSpecializations: ["Chirurgie artroscopică", "Proteză de șold", "Proteză de genunchi"],
    languages: ["Română", "Engleză"],
    certifications: ["Certificat European de Ortopedie", "Certificat în Chirurgie Artroscopică"],
  },
  {
    image: "/assets/images/f_39.png",
    name: "Dr. Ana-Maria Constantinescu",
    specialty: "Pediatrie",
    age: 39,
    education: [
      { degree: "Doctorat în Medicină", institution: "Universitatea de Medicină și Farmacie Carol Davila", country: "România", year: 2008 },
      { degree: "Specializare Pediatrie", institution: "Spitalul de Urgență pentru Copii Maria Sklodowska Curie", country: "România", year: 2013 },
      { degree: "Fellowship Neonatologie", institution: "Children's Hospital of Philadelphia", country: "Străinătate", year: 2015 },
    ],
    experience: 12,
    additionalSpecializations: ["Neonatologie", "Pediatrie generală", "Vaccinări"],
    languages: ["Română", "Engleză", "Franceză"],
    certifications: ["Certificat European de Pediatrie", "Certificat în Neonatologie"],
  },
  {
    image: "/assets/images/b_44.png",
    name: "Dr. Bogdan Nistor",
    specialty: "Psihiatrie",
    age: 44,
    education: [
      { degree: "Doctorat în Medicină", institution: "Universitatea de Medicină și Farmacie Carol Davila", country: "România", year: 2003 },
      { degree: "Specializare Psihiatrie", institution: "Spitalul Universitar de Psihiatrie Prof. Dr. Alexandru Obregia", country: "România", year: 2008 },
      { degree: "Fellowship Psihiatrie a Copilului și Adolescentului", institution: "Harvard Medical School", country: "Străinătate", year: 2011 },
    ],
    experience: 17,
    additionalSpecializations: ["Psihiatrie a copilului", "Psihoterapie", "Psihofarmacologie"],
    languages: ["Română", "Engleză"],
    certifications: ["Certificat European de Psihiatrie", "Certificat în Psihiatrie a Copilului"],
  },
  {
    image: "/assets/images/f_41.png",
    name: "Dr. Ioana Petrescu",
    specialty: "Urologie",
    age: 41,
    education: [
      { degree: "Doctorat în Medicină", institution: "Universitatea de Medicină și Farmacie Carol Davila", country: "România", year: 2006 },
      { degree: "Specializare Urologie", institution: "Spitalul Universitar de Urgență București", country: "România", year: 2011 },
      { degree: "Fellowship Urologie Oncologică", institution: "Memorial Sloan Kettering Cancer Center", country: "Străinătate", year: 2013 },
    ],
    experience: 14,
    additionalSpecializations: ["Urologie oncologică", "Urologie feminină", "Chirurgie minim invazivă"],
    languages: ["Română", "Engleză"],
    certifications: ["Certificat European de Urologie", "Certificat în Urologie Oncologică"],
  },
  {
    image: "/assets/images/b_52.png",
    name: "Dr. Radu Vasilescu",
    specialty: "Cardiologie",
    age: 52,
    education: [
      { degree: "Doctorat în Medicină", institution: "Universitatea de Medicină și Farmacie Iuliu Hațieganu Cluj-Napoca", country: "România", year: 1996 },
      { degree: "Specializare Cardiologie", institution: "Institutul de Boli Cardiovasculare Cluj-Napoca", country: "România", year: 2001 },
      { degree: "Fellowship Electrofiziologie", institution: "Cleveland Clinic", country: "Străinătate", year: 2004 },
    ],
    experience: 24,
    additionalSpecializations: ["Electrofiziologie", "Aritmii cardiace", "Stimulare cardiacă"],
    languages: ["Română", "Engleză", "Maghiară"],
    certifications: ["Certificat European de Cardiologie", "Certificat în Electrofiziologie"],
  },
  {
    image: "/assets/images/b_43.png",
    name: "Dr. Mihai Tănase",
    specialty: "Cardiologie",
    age: 43,
    education: [
      { degree: "Doctorat în Medicină", institution: "Universitatea de Medicină și Farmacie Carol Davila", country: "România", year: 2004 },
      { degree: "Specializare Cardiologie", institution: "Spitalul Universitar de Urgență București", country: "România", year: 2009 },
      { degree: "Fellowship Insuficiență Cardiacă", institution: "Brigham and Women's Hospital", country: "Străinătate", year: 2012 },
    ],
    experience: 16,
    additionalSpecializations: ["Insuficiență cardiacă", "Transplant cardiac", "Ecocardiografie avansată"],
    languages: ["Română", "Engleză"],
    certifications: ["Certificat European de Cardiologie", "Certificat în Insuficiență Cardiacă"],
  },
  {
    image: "/assets/images/f_37.png",
    name: "Dr. Simona Marin",
    specialty: "Dermatologie",
    age: 37,
    education: [
      { degree: "Doctorat în Medicină", institution: "Universitatea de Medicină și Farmacie Carol Davila", country: "România", year: 2010 },
      { degree: "Specializare Dermatologie", institution: "Spitalul Universitar de Urgență București", country: "România", year: 2015 },
      { degree: "Fellowship Dermatologie Pediatrică", institution: "Great Ormond Street Hospital", country: "Străinătate", year: 2017 },
    ],
    experience: 10,
    additionalSpecializations: ["Dermatologie pediatrică", "Alergii cutanate", "Dermatoscopie digitală"],
    languages: ["Română", "Engleză"],
    certifications: ["Certificat European de Dermatologie", "Certificat în Dermatologie Pediatrică"],
  },
  {
    image: "/assets/images/b_39.png",
    name: "Dr. Cătălin Olteanu",
    specialty: "Endocrinologie",
    age: 47,
    education: [
      { degree: "Doctorat în Medicină", institution: "Universitatea de Medicină și Farmacie Grigore T. Popa Iași", country: "România", year: 2000 },
      { degree: "Specializare Endocrinologie", institution: "Institutul de Endocrinologie C.I. Parhon", country: "România", year: 2005 },
      { degree: "Fellowship Boli Metabolice", institution: "Mayo Clinic", country: "Străinătate", year: 2008 },
    ],
    experience: 20,
    additionalSpecializations: ["Boli metabolice", "Obezitate", "Boli tiroidiene autoimune"],
    languages: ["Română", "Engleză", "Franceză"],
    certifications: ["Certificat European de Endocrinologie", "Certificat în Boli Metabolice"],
  },
  {
    image: "/assets/images/f_36.png",
    name: "Dr. Diana Gheorghe",
    specialty: "Gastroenterologie",
    age: 36,
    education: [
      { degree: "Doctorat în Medicină", institution: "Universitatea de Medicină și Farmacie Carol Davila", country: "România", year: 2011 },
      { degree: "Specializare Gastroenterologie", institution: "Spitalul Universitar de Urgență București", country: "România", year: 2016 },
      { degree: "Fellowship Hepatologie", institution: "Johns Hopkins Hospital", country: "Străinătate", year: 2018 },
    ],
    experience: 9,
    additionalSpecializations: ["Hepatologie", "Boli hepatice cronice", "Transplant hepatic"],
    languages: ["Română", "Engleză"],
    certifications: ["Certificat European de Gastroenterologie", "Certificat în Hepatologie"],
  },
  {
    image: "/assets/images/b_37.png",
    name: "Dr. Adrian Stoica",
    specialty: "Neurologie",
    age: 49,
    education: [
      { degree: "Doctorat în Medicină", institution: "Universitatea de Medicină și Farmacie Iuliu Hațieganu Cluj-Napoca", country: "România", year: 1999 },
      { degree: "Specializare Neurologie", institution: "Spitalul Clinic de Neurologie Cluj-Napoca", country: "România", year: 2004 },
      { degree: "Fellowship Scleroză Multiplă", institution: "National Hospital for Neurology and Neurosurgery", country: "Străinătate", year: 2007 },
    ],
    experience: 21,
    additionalSpecializations: ["Scleroză multiplă", "Neurologie demielinizantă", "Neuroimunologie"],
    languages: ["Română", "Engleză", "Maghiară"],
    certifications: ["Certificat European de Neurologie", "Certificat în Scleroză Multiplă"],
  },
  {
    image: "/assets/images/f_35.png",
    name: "Dr. Laura Popa",
    specialty: "Analize medicale",
    age: 35,
    education: [
      { degree: "Doctorat în Medicină", institution: "Universitatea de Medicină și Farmacie Carol Davila", country: "România", year: 2012 },
      { degree: "Specializare Medicină de Laborator", institution: "Institutul Național de Sănătate Publică", country: "România", year: 2017 },
      { degree: "Master în Biochimie Clinică", institution: "University of Cambridge", country: "Străinătate", year: 2019 },
    ],
    experience: 8,
    additionalSpecializations: ["Biochimie clinică", "Hematologie", "Microbiologie medicală"],
    languages: ["Română", "Engleză"],
    certifications: ["Certificat European de Medicină de Laborator", "Certificat în Biochimie Clinică"],
  },
];

export const StatusIcon = {
  scheduled: "/assets/icons/check.svg",
  pending: "/assets/icons/pending.svg",
  cancelled: "/assets/icons/cancelled.svg",
};
