apiVersion: apps/v1
kind: Deployment
metadata:
  name: carepulse
spec:
  template:
    spec:
      containers:
        - name: app
          volumeMounts:
            - name: carepulse-data
              mountPath: /app/data
      volumes:
        - name: carepulse-data
          persistentVolumeClaim:
            claimName: carepulse-data

