apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secrets
  labels:
    app.kubernetes.io/name: postgresql
type: Opaque
stringData:
  POSTGRES_DB: carepulse
  POSTGRES_USER: carepulse
  POSTGRES_PASSWORD: change-me

