[kube_control_plane]
cp1 ansible_host=192.168.10.10 node_ip=192.168.10.10

[kube_workers]
worker1 ansible_host=192.168.10.21 node_ip=192.168.10.21
worker2 ansible_host=192.168.10.22 node_ip=192.168.10.22

[k8s_cluster:children]
kube_control_plane
kube_workers

