apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: carepulse

resources:
  - redis-secret.yaml
  - redis-persistentvolumeclaim.yaml
  - redis-service.yaml
  - redis-deployment.yaml
  - redis-networkpolicy.yaml
