apiVersion: v1
kind: Secret
metadata:
  name: redis-auth
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: carepulse
type: Opaque
stringData:
  redis-password: change-me-redis-password
